### ISSUE TITLE
Unable to connect to RabbitMQ via steeltoe connector from .net core console application

### ISSUE THREAD

**Issue by sajanep** [SteeltoeOSS/Connectors#22]
I am trying to create a .net core 2.0 console application to connect to a rabbitmq instance in PCF. I am using the latest steeltoe connectors 2.1.0. Unfortunately I am not able to connect using AddRabbitMQConnection() and getting below exception when running in PCF. Basically it is not connection, but configuring ConnectionFactory with user provided service.

```
2018-10-09T17:02:58.849+05:30 [APP/TASK/execute-dlqprcoessing-task/0] [ERR] Unhandled Exception: System.InvalidOperationException: Failed to convert '' to type 'System.Int32'. ---> System.Exception: is not a valid value for Int32. ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
2018-10-09T17:02:58.849+05:30 [APP/TASK/execute-dlqprcoessing-task/0] [ERR] at System.ComponentModel.BaseNumberConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
2018-10-09T17:02:58.849+05:30 [APP/TASK/execute-dlqprcoessing-task/0] [ERR] --- End of inner exception stack trace ---
2018-10-09T17:02:58.849+05:30 [APP/TASK/execute-dlqprcoessing-task/0] [ERR] at Microsoft.Extensions.Configuration.ConfigurationBinder.TryConvertValue(Type type, String value, Object& result, Exception& error)
2018-10-09T17:02:58.849+05:30 [APP/TASK/execute-dlqprcoessing-task/0] [ERR] at Microsoft.Extensions.Configuration.ConfigurationBinder.BindInstance(Type type, Object instance, IConfiguration config)
2018-10-09T17:02:58.849+05:30 [APP/TASK/execute-dlqprcoessing-task/0] [ERR] at Microsoft.Extensions.Configuration.ConfigurationBinder.BindProperty(PropertyInfo property, Object instance, IConfiguration config)
2018-10-09T17:02:58.849+05:30 [APP/TASK/execute-dlqprcoessing-task/0] [ERR] at Microsoft.Extensions.Configuration.ConfigurationBinder.BindNonScalar(IConfiguration configuration, Object instance)
2018-10-09T17:02:58.849+05:30 [APP/TASK/execute-dlqprcoessing-task/0] [ERR] at Microsoft.Extensions.Configuration.ConfigurationBinder.Bind(IConfiguration configuration, Object instance)
2018-10-09T17:02:58.849+05:30 [APP/TASK/execute-dlqprcoessing-task/0] [ERR] at Steeltoe.CloudFoundry.Connector.CloudFoundryServiceInfoCreator.BuildServiceInfos()
2018-10-09T17:02:58.849+05:30 [APP/TASK/execute-dlqprcoessing-task/0] [ERR] at Steeltoe.CloudFoundry.Connector.CloudFoundryServiceInfoCreator.Instance(IConfiguration config)
2018-10-09T17:02:58.849+05:30 [APP/TASK/execute-dlqprcoessing-task/0] [ERR] at Steeltoe.CloudFoundry.Connector.IConfigurationExtensions.GetServiceInfos[SI](IConfiguration config)
2018-10-09T17:02:58.849+05:30 [APP/TASK/execute-dlqprcoessing-task/0] [ERR] at Steeltoe.CloudFoundry.Connector.IConfigurationExtensions.GetSingletonServiceInfo[SI](IConfiguration config)
2018-10-09T17:02:58.849+05:30 [APP/TASK/execute-dlqprcoessing-task/0] [ERR] at Steeltoe.CloudFoundry.Connector.RabbitMQ.RabbitMQProviderServiceCollectionExtensions.AddRabbitMQConnection(IServiceCollection services, IConfiguration config, ServiceLifetime contextLifetime, ILoggerFactory logFactory)
```
My console application code looks like below
```
static void Main(string[] args)
        {
          var envName = Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT");

            var cfgBuilder = new ConfigurationBuilder()
               .SetBasePath(Directory.GetCurrentDirectory())
               .AddEnvironmentVariables()
               .AddJsonFile("appsettings.json", true, false)
               .AddJsonFile($"appsettings.{envName}.json", true, false)
               .AddCloudFoundry();
            var configuration = cfgBuilder.Build();

            var serviceCollection = new ServiceCollection();

            // Configure services for DI
            ConfigureServices(serviceCollection, configuration);

            var serviceProvider = serviceCollection.BuildServiceProvider();
            var worker = serviceProvider.GetRequiredService<Worker>();
            Console.WriteLine("Started reading from queue");
            worker.Receieve();

            Console.WriteLine("Finished executing task!");
        }

        private static void ConfigureServices(IServiceCollection services, IConfiguration configuration)
        {
            // add logging
            services.AddSingleton(new LoggerFactory()
            .AddConsole(configuration.GetSection("Logging"))
            .AddDebug());

            // Read the configuration from app settings. If not found,  use pcf version of rabbitmq
            var connectionConfig = configuration.GetSection("ConnectionFactory").Get<RabbitMqConnectionConfig>();
            if (connectionConfig != null)
            {
                var factory = new ConnectionFactory
                {
                    VirtualHost = connectionConfig.VirtualHost,
                    HostName = connectionConfig.HostName,
                    Port = Convert.ToInt32(connectionConfig.Port),
                    UserName = connectionConfig.UserName,
                    Password = connectionConfig.Password
                };
                services.AddSingleton<IConnectionFactory>(c => factory);
            }
            else
            {
                // use the steel-toe connector
                Console.WriteLine("Trying to connect to RabbitMQ via steeltoe connector!");
                services.AddRabbitMQConnection(configuration);
                Console.WriteLine("Connected to RabbitMQ via steeltoe connector!");
            }

            // add worker
            services.AddSingleton<Worker>();
        }
    }
```
I am using below packages

```
<PackageReference Include="Steeltoe.Extensions.Configuration.CloudFoundryCore" Version="2.1.0" />
 <PackageReference Include="RabbitMQ.Client" Version="5.1.0" />
 <PackageReference Include="Steeltoe.CloudFoundry.ConnectorCore" Version="2.1.0" />
```
Any idea what I am doing wrong. Steeltoe official samples are using asp.net core applications

**Comment by TimHess** [comment]
Is this a long-running console application, or are you running it via cf run-task?

**Comment by TimHess** [comment]
Also, can you share the structure or contents of the node in `vcap:services` that describes the RabbitMQ service info for the application?

**Comment by sajanep** [comment]
> Is this a long-running console application, or are you running it via cf run-task?

I am running via cf run-task and actually wanted to convert to a scheduled job

**Comment by sajanep** [comment]
> Also, can you share the structure or contents of the node in `vcap:services` that describes the RabbitMQ service info for the application?

My console apps env. variable looks something like below

```
{
  "staging_env_json": {},
  "running_env_json": {},
  "system_env_json": {
    "VCAP_SERVICES": {
      "user-provided": [
        {
          "name": "syslog-drain",
          "instance_name": "syslog-drain",
          "binding_name": null,
          "credentials": {},
          "syslog_drain_url": "syslog://myserver:6500",
          "volume_mounts": [],
          "label": "user-provided",
          "tags": []
        }
      ],
      "cf-rabbitmq": [
        {
          "name": "RabbitTest",
          "instance_name": "RabbitTest",
          "binding_name": null,
          "credentials": {
            "http_api_uris": [
              "https://f0af37bb-4d11-47a0-b228-b5ee58ec004b:/"
            ],
            "ssl": false,
            "dashboard_url": "https://cf-rabbitmq.cft/#/login/f0af37bb-4d11-47a0-b228-b5ee58ec004b/ir3edmb0kbn7fgdst1qee4sk97",
            "password": "iee4sk97",
            "protocols": {
              "amqp": {
                "vhost": "ad9fc636-79dd8bc37cf13c",
                "username": "f0af37bb-4d11-ee58ec004b",
                "password": "ir3edmb0kbqee4sk97",
                "port": 5672,
                "host": "10.10.10.10",
                "hosts": [
                  "10.10.10.10",
                  "10.10.10.10"
                ],
```

**Comment by TimHess** [comment]
OK, this seems to be related to #19 then -- are you running on PAS or PASW?

**Comment by sajanep** [comment]
I guess PAS. Hope you meant Pivotal Application Service. Sorry I did not get what is PASW?

**Comment by TimHess** [comment]
Oh - sorry the basic question is Linux (PAS) or Windows (PASW). Are you using the dotnet core buildpack?

It might also help to know what versions you're on for the buildpack and PCF/PAS if you can get that info as well

**Comment by TimHess** [comment]
Connectors 2.1.1 is out on nuget.org and in my testing was able to resolve this issue, please let me know if it does not work for you!

**Comment by brcorbin** [comment]
I had the same issue and 2.1.1 fixed it for me.  Thanks!

**Comment by sajanep** [comment]
> Oh - sorry the basic question is Linux (PAS) or Windows (PASW). Are you using the dotnet core buildpack?
> 
> It might also help to know what versions you're on for the buildpack and PCF/PAS if you can get that info as well

Hello,
Sorry about my lack of knowledge. I am targeting cflinuxfs2 stack and using dotnet core buildpack

**Comment by sajanep** [comment]
> Connectors 2.1.1 is out on nuget.org and in my testing was able to resolve this issue, please let me know if it does not work for you!

Hello Tim,
Awesome. I tried at my end and it is working. Thanks a lot.

**Comment by TimHess** [comment]
> > Oh - sorry the basic question is Linux (PAS) or Windows (PASW). Are you using the dotnet core buildpack?
> > It might also help to know what versions you're on for the buildpack and PCF/PAS if you can get that info as well
> 
> Hello,
> Sorry about my lack of knowledge. I am targeting cflinuxfs2 stack and using dotnet core buildpack

Don't worry about it - I was considering trying to track it down on the buildpack side because, at least from the cf run-task documentation, the environment is _supposed_ to be the same as it is for the running app. Ultimately the variables that caused the exceptions (eg: Port) don't make sense in this context. Steeltoe was making some assumptions for them that didn't work out, so it didn't seem worth it to track the issue much further given how simple it was to fix from our side.

Closing the issue as it seems to be resolved. Thanks for reporting!
